USE cliTest;

DROP TABLE IF EXISTS NewEmployees;

CREATE TABLE NewEmployees ( 
	EMPLOYEE_ID INTEGER NOT NULL,
	EMPLOYEE_NAME VARCHAR(25) NOT NULL,
	EMAIL VARCHAR(25) NOT NULL,
	HIRE_DATE DATE NOT NULL,
	SALARY DOUBLE(8,2)
);


